### ISSUE TITLE
Update to asynchronous API for VS 2019

### ISSUE THREAD

**Issue by NN---** [mayerwin/vs-customize-window-title#31]
https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/

**Comment by mayerwin** [comment]
Thanks, I'll push a fix when the first RC is out.

**Comment by rizi** [comment]
Will the current version work with VS 2019? Br

**Comment by mayerwin** [comment]
I don't know, likely not, this is why I mentioned I'll release a new version by then.

**Comment by rizi** [comment]
OK, I was just asking because you sayed "Thanks, I'll push a fix when the first RC is out." and it's released 1 or 2 weeks ago and on the project site (https://marketplace.visualstudio.com/items?itemName=mayerwin.RenameVisualStudioWindowTitle) it states compatible with VS 2019. (no offense!, I just wanted to know).
br

**Comment by mayerwin** [comment]
Oh OK, I wasn't aware of this. Thanks! I'll work on this next weekend.

**Comment by mayerwin** [comment]
This has been implemented in 4.0.1 and is working, however I am unable to upload it to the gallery for some reason. However in the meantime I've been able to see that the current synchonous version still works. It just shows a warning that can be disabled.

**Comment by rizi** [comment]
@mayerwin big thx

**Comment by mayerwin** [comment]
I have been able to upload it to the gallery.
