### ISSUE TITLE
Extension causes VS to freeze sporadically

### ISSUE THREAD

**Issue by amorpheus** [mayerwin/vs-customize-window-title#42]
I've seen the "this extension has caused X seconds of unresponsiveness" warning multiple times today, for version 4.3.0. First time was 5, just a few minutes ago it was 6.

The only settings I've changed from defaults were the "solution in X mode" ones:
[solutionName] [[tfsBranchName]] (Debugging) - [ideName]
[solutionName] [[tfsBranchName]] - [ideName]
[solutionName] [[tfsBranchName]] (Running) - [ideName]

I've turned on the Debug option and can hopefully contribute something more substantial when this happens again.

**Comment by mayerwin** [comment]
Can you confirm what is your version of Visual Studio, and if you're using other extensions?

**Comment by mayerwin** [comment]
If the issue is consistent, it'd be good if you can temporarily try removing [tfsBranchName] from the pattern to see if this is related to this tag (which does take some time to resolve, though normally it should be asynchronous).

**Comment by amorpheus** [comment]
Microsoft Visual Studio Professional 2017 
Version 15.9.11
VisualStudio.15.Release/15.9.11+28307.586
Microsoft .NET Framework
Version 4.7.03190

I'll try removing the branch tag and see how it goes.

**Comment by mayerwin** [comment]
For reference: https://resharper-support.jetbrains.com/hc/en-us/articles/115001013390--We-ve-noticed-that-extension-ReSharper-Ultimate-is-slowing-Visual-Studio-message-

**Comment by mayerwin** [comment]
Hum, it is very much possible that [tfsBranchName] is causing the slowness, as it is the only tag that needs to run on the UI thread for the resolution:

`Globals.InvokeOnUIThread(() => name = TfsHelper.GetBranchNameFromLocalFile(Path.GetDirectoryName(sn)));`

I need to check if there is a way to run it outside the UI thread, but I remember I added this invoke because it was otherwise throwing exceptions.

**Comment by mayerwin** [comment]
https://github.com/mayerwin/vs-customize-window-title/blob/master/CustomizeVSWindowTitle/Resolvers/TfsBranchResolver.cs

**Comment by amorpheus** [comment]
Thanks for the updates. Is resolving the branch name something that needs to ping the TFS server, or where could the slowness happen?

**Comment by mayerwin** [comment]
Yes, apparently with TFS it needs to ping the server, which is slow. But this alone is not a problem. The problem is if we have to run this on the UI thread.

**Comment by mayerwin** [comment]
Do you think I could cache the result of the branch name for a particular solution file?

**Comment by mayerwin** [comment]
Is it guaranteed to not change (my instinct tells me that it can change if the branch is switched while the solution is still open in Visual Studio)?

**Comment by amorpheus** [comment]
Personally, I don't think I would ever need my VS title to adapt to a new branch name after opening a solution. Maybe checking the branch name could depend on other variables that trigger it?

**Comment by mayerwin** [comment]
I prefer to be safe and always recheck if it can change (otherwise it can cause bad surprises for users). Since the branch name change could be triggered outside of VS, I'm afraid there is no event we can hook to to refresh only when strictly needed. But anyway it shouldn't be a problem if we can run this asynchronously.

Can you try the following release 4.3.1, where I am running the offending line on the threadpool thread, and let me know if you see any error in the debug or notice any slowness, or crash?

[CustomizeVSWindowTitle (4.3.1).vsix.zip](https://github.com/mayerwin/vs-customize-window-title/files/3044493/CustomizeVSWindowTitle.4.3.1.vsix.zip)

Just extract the vsix file (GitHub doesn't allow to upload vsix files) and install it, it should overwrite the existing version (and keep the link with the auto update if I push a new version on the gallery.

**Comment by amorpheus** [comment]
Got it running now and it seems to work just fine. :)
Thanks!
